### ISSUE TITLE
volume number not appearing in preview

### ISSUE THREAD

**Issue by thwmurph** [iucogs/pubs#11]
I don't know how big of an issue this really is, but something I've noticed for awhile is that whenever there's something that is a particular volume of something, it never actually shows up in the 'preview' section when I actually put the volume number in the 'volume' space. it may very well show up in the actual citations for the site, I'm not sure, but as far as what the 'preview' is telling me, it isn't there.

**Comment by pjcraig** [comment]
Hey Tom,

I'll take a look at this today.

-- Patrick

**Comment by pjcraig** [comment]
Looks like this depends on the type of publication.

**Comment by pjcraig** [comment]
So generally preview is pretty much a copy of what gets printed. And although the information is in the database, when the citation is exported, the volume information isn't printed.

This gets tricky in books, though, because the volume comes before any subtitles and right now we don't have a way of distinguishing those.

Continuing to look into this one.

**Comment by pjcraig** [comment]
fixed and pushed to master
